version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1 
    commands:
      - dotnet tool install -g Amazon.ElasticBeanstalk.Tools
      - dotnet restore
  build:
    commands:
      - cd test-dotnet-app-mvc
      - dotnet eb package
artifacts:
  files:
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/runtimes/unix/lib/netcoreapp2.1/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/runtimes/win/lib/netcoreapp2.1/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/runtimes/win/lib/netstandard2.0/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/bootstrap/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/bootstrap/dist/css/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/bootstrap/dist/js/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/jquery/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/jquery/dist/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/jquery-validation/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/jquery-validation/dist/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/lib/jquery-validation-unobtrusive/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/css/*
    - test-dotnet-app-mvc/bin/Release/netcoreapp3.1/wwwroot/js/*
  discard-paths: yes
