version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1 
    commands:
      - dotnet tool install -g Amazon.ElasticBeanstalk.Tools
  build:
    commands:
      - cd test-dotnet-app-mvc
      - dotnet eb package
artifacts:
  files:
    - ./test-dotnet-app-mvc/bin/Release/netcoreapp3.1/publish/*
  discard-paths: yes
