version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1 
    commands:
      - dotnet tool install -g Amazon.ElasticBeanstalk.Tools
      - dotnet restore
  build:
    commands:
      - cd test-dotnet-app-mvc
      - dotnet publish -c release -o ./build_output test-dotnet-app-mvc.csproj
artifacts:
  files:
    - ./build_output/*
  discard-paths: yes
